### ISSUE TITLE
Update URLs to point to /latest/

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-spreadsheet-template#10]
Currently the URLs in README.md point to the `dev` branch. Once version 0.2 is released we should update the URLS to point to `latest`.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/GFDRR/rdls-spreadsheet-template/commit/479376ced07da8cf0ec799716b8eb921253cb507

I've also updated the templates for the 0.2.0 release in https://github.com/GFDRR/rdls-spreadsheet-template/commit/06dd36e0f49ca8f9c9279457406f87211b3f1247

**Comment by stufraser1** [comment]
references in spreadsheet template are not working correctly:

all follow this example: 
https://docs.riskdatalibrary.org/reference/...
instead of:
https://docs.riskdatalibrary.org/en/latest/reference/...

Results of search suggest this is all links: 73 found
<img width="675" alt="image" src="https://github.com/GFDRR/rdls-spreadsheet-template/assets/12515042/312c78f5-e930-4f76-b168-4ae8eb4cdd23">

full temaplte tested, four individual-component templates not tested.

**Comment by odscjen** [comment]
@duncandewhurst leaving this to you. I tried generating new version but ran into an error with requirements.txt

> Processing /mnt/9E863086863060C7/GDrive/Work/Repositories/risk_data_library/rdls-spreadsheet-template/flatten-tool (from -r requirements.txt (line 31))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/mnt/9E863086863060C7/GDrive/Work/Repositories/risk_data_library/rdls-spreadsheet-template/flatten-tool'

**Comment by duncandewhurst** [comment]
@stufraser1 I've fixed the codelist links in https://github.com/GFDRR/rdls-spreadsheet-template/commit/339e70d2b9c545d5a514295dca29fcf02ba46414 please reopen the issue if there's a still a problem

@odscjen you first need to initialise submodules by running `git submodule init`. I've added instructions for setting up your development environment to the readme: https://github.com/GFDRR/rdls-spreadsheet-template#set-up-your-development-environment. Please open a new issue if you're still having problems.
