### ISSUE TITLE
New version for testing

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-spreadsheet-template#3]
I've pushed an [updated version of the template](https://raw.githubusercontent.com/GFDRR/rdls-spreadsheet-template/main/templates/full.xlsx) to this repository and I've updated the [Google Docs copy](https://docs.google.com/spreadsheets/d/13nB3FghTfSqb-PIGs5sA4Q0iMI1j63pWg0-zd82puWo/) too.

@matamadio please use this version for testing. The issues you flagged in the old version should be resolved now. Let me know if you spot any other problems.

In addition to fixing those issues, I also updated the formatting and implemented data validation for id fields so you need only enter each identifier once, in it's 'parent' worksheet (e.g. `datasets`). When referring to an identifier from another worksheet (e.g. `resources`), you can select the identifier from a drop-down list.

The updated version of the template is based on the schema from https://github.com/GFDRR/rdl-standard/pull/181, which includes a few fixes for issues that I noticed whilst working on the template.

**Comment by matamadio** [comment]
Thanks, I'm testing it.

One preliminary question: how are the enums loaded now? I don't see the enum tab anymore, but can't figure out how the magic works.

**Comment by matamadio** [comment]
### Example for HAZARD: Fathom country dataset

https://docs.google.com/spreadsheets/d/1QrkzeAWIFM8ELEoME4YjfhQp4j68wX9g/edit?usp=sharing&ouid=104127175378111601700&rtpof=true&sd=true

Note:
- non-hazard tabs and fields have been dropped
- not all tabs and attributes are filled; required + some others
- license is missing as "commercial" attribution is not listed in codelist
- not quite sure if I got the id branching right:
  - I have one dataset made of 3 resources (id 1,2,3).
  - Each of these resources are described by corresponding hazard_events_set (id 1,2,3).
    - They are identified by two type of processes:
      - hazard_events_set 1 and 2 are fluvial flood, 3 is pluvial.
      - then hazard/event_sets/0/hazards/0/id is (1;1;2)
  - Within each hazard_events_set, we have 10 different probabilistic scenarios each (hazard/event_sets/0/events/0/id 1 to 10)

**Comment by matamadio** [comment]
Example for EXPOSURE: GHS builtup dataset (Thailand)

[Exposure template on Gdocs](https://docs.google.com/spreadsheets/d/1t2-p8ZPFIWzjt8Q868X96es8MMb4KYIF/edit?usp=sharing&ouid=104127175378111601700&rtpof=true&sd=true)

Note:
- non-exposure tabs and fields have been dropped
- for IANA codelist indicating related publication, i used
  `"describedby": Refers to a resource providing information about the link's context.`
- exposure/cost/0/unit should not be Required
  - eg building layers having just area values, not an economic attribute

**Comment by duncandewhurst** [comment]
Thanks for the feedback! I'll respond to the points that are specific to the template here.

@odscjen please can you:

1. Create issues on https://github.com/GFDRR/rdl-standard for the points that are related to the schema.
2. Convert and validate the examples provided by Mat (per https://github.com/GFDRR/rdls-spreadsheet-template/issues/4) and share your feedback 

> One preliminary question: how are the enums loaded now? I don't see the enum tab anymore, but can't figure out how the magic works.

The enum tab is there but hidden to prevent accidental edits. You should be able to unhide it if you need to. Let me know if you run into problems.

> This is nice; yet looks like the parent id field gets duplicated. I'm removing it manually.

Ah, thanks for flagging. I will fix it in the next iteration. I've created an issue: https://github.com/GFDRR/rdls-spreadsheet-template/issues/6

**Comment by duncandewhurst** [comment]
> * for IANA codelist indicating related publication, i used
>   `"describedby": Refers to a resource providing information about the link's context.`

'describedby' is used to link to the schema that describes that RDLS metadata so it probably isn't the right code here. What is the relationship between the related publication and the dataset? Does it fit the semantics of `referencedBy` or `sources`?

**Comment by matamadio** [comment]
`'describedby' is used to link to the schema that describes that RDLS metadata so it probably isn't the right code here. What is the relationship between the related publication and the dataset? Does it fit the semantics of referencedBy or sources?`
Right, then I should use `sources`. I'll update the file on gdrive.

**Comment by matamadio** [comment]
@odscjen you should have edit access to the [folder](https://drive.google.com/drive/folders/1V33k5YmYjcvjFnYpx7chOx-PeSivYRWm?usp=sharing).

**Comment by odscjen** [comment]
great, thanks :)

**Comment by odscjen** [comment]
@duncandewhurst an odd thing in the flatten-tool converted version of the [Hazard example](https://github.com/GFDRR/rdls-spreadsheet-template/issues/3#issuecomment-1671222026)

`referenced_by.author_names` is an array within an array, as is `spatial.bbox`
```json
"referenced_by": [
        {
            "id": "1",
            "name": "A high-resolution global flood hazard model",
            "authorNames": [
                [
                    "Christopher C. Sampson",
                    " Andrew M. Smith",
                    " Paul D. Bates",
                    " Jeffrey C. Neal",
                    " Lorenzo Alfieri",
                    " Jim E. Freer"
                ]
            ],
            "datePublished": "2015-08-18",
            "url": "https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015WR016954",
            "doi": "10.1002/2015WR016954"
        }
    ],
```
and
```json
"bbox": [
            [
                96.72037,
                5.407344,
                105.72785,
                20.718323
            ]
        ],
```
but it looks right in the spreadsheet?

**Comment by odscjen** [comment]
@matamadio re comment above

> not quite sure if I got the id branching right: 

It looks like you did get the branching right :)

**Comment by duncandewhurst** [comment]
> @duncandewhurst an odd thing in the flatten-tool converted version of the [Hazard example](https://github.com/GFDRR/rdls-spreadsheet-template/issues/3#issuecomment-1671222026)

Yep, that's due to the Flatten Tool bug I mentioned in https://github.com/GFDRR/rdls-spreadsheet-template/issues/4. I've opened an issue on Flatten Tool to get it fixed. Looks like the data has been entered correctly in the spreadsheet, albeit with extra whitespace before each author's name.

**Comment by odscjen** [comment]
ah, cool, I ignored all the other errors reported due to that mentioned bug but hadn't picked up that this was part of the same thing. I see you've reported it in the flatten-tool repo, thank you!

**Comment by duncandewhurst** [comment]
> > @duncandewhurst an odd thing in the flatten-tool converted version of the [Hazard example](https://github.com/GFDRR/rdls-spreadsheet-template/issues/3#issuecomment-1671222026)
> 
> Yep, that's due to the Flatten Tool bug I mentioned in #4. I've opened an issue on Flatten Tool to get it fixed. Looks like the data has been entered correctly in the spreadsheet, albeit with extra whitespace before each author's name.

I was mistaken, it's not a bug. The correct syntax is a semicolon-separated list, rather than a comma-separated list.

@matamadio I've just pushed a new version of the template ([XLSX](https://github.com/GFDRR/rdls-spreadsheet-template/raw/main/templates/full.xlsx), [GSheets](https://docs.google.com/spreadsheets/d/13nB3FghTfSqb-PIGs5sA4Q0iMI1j63pWg0-zd82puWo/edit#gid=661644817)) with the following additions and improvements:

- Add a basic README sheet
- Add codelist hyperlinks
- Add data input guidance
- Update error messages for array fields
- Auto-populate and hide the links sheet
- Permit additional values for open codelists, add error messages
- Remove duplicate id fields

Please can you test it. I think this is all we can add in terms of features, but we can fix any bugs and improve the documentation.

**Comment by odscjen** [comment]
entering as a semi-colon seperated list looks like this in the flatten-tool output (from Mat's Exposure example last week):

```json 
"referenced_by": [
                {
                    "id": "1",
                    "name": " GHS-BUILT-S R2023A - GHS built-up surface grid, derived from Sentinel2 composite and Landsat, multitemporal (1975-2030)",
                    "authorNames": [
                        [
                            "Pesaresi",
                            " Martino"
                        ],
                        [
                            " Politis",
                            " Panagiotis"
                        ]
                    ],
                    "datePublished": "2023",
                    "url": "http://data.europa.eu/89h/9f06f36f-4b11-47ec-abb0-4f8b7b1d72ea",
                    "doi": "10.2905/9F06F36F-4B11-47EC-ABB0-4F8B7B1D72EA"
                }
            ]
```
so it's still creating array's within array's which can't be right?

**Comment by odscjen** [comment]
Realised what's wrong above, it's the combination of commas and semi colons. It's best then to give the author names without a common, so "Jen Harris" or "J Harris" or "J. Harris" rather than "Harris, Jen"

**Comment by duncandewhurst** [comment]
I've asked the devs what the correct syntax is in https://github.com/OpenDataServices/flatten-tool/issues/427. If it isn't possible to include commas or semi-colons within the values, we can update the input guidance for array fields and add a data validation warning if the cell's value includes commas or semi-colons.

**Comment by matamadio** [comment]
Latest split templates and examples for hazard and exposure (real data).

https://drive.google.com/drive/folders/1V33k5YmYjcvjFnYpx7chOx-PeSivYRWm?usp=sharing

**Comment by duncandewhurst** [comment]
@matamadio, a couple of questions on the [Global Human Settlement layer (Thailand) example](https://docs.google.com/spreadsheets/d/1SY0RFWhsIcpr_WSy1aRGhGBKoQkwSCFf/edit#gid=633469357):

1. What is the reason for listing the Thailand data a dataset, rather than just listing the whole [GHS-BUILT-S R2023A - GHS built-up surface grid, derived from Sentinel2 composite and Landsat, multitemporal (1975-2030) dataset](https://data.jrc.ec.europa.eu/dataset/9f06f36f-4b11-47ec-abb0-4f8b7b1d72ea) in line with the listing in the EU Joint Research Centre Data Catalogue?
2. Why is the [`exposure_cost` sheet](https://docs.google.com/spreadsheets/d/1SY0RFWhsIcpr_WSy1aRGhGBKoQkwSCFf/edit#gid=1909140703) populated? If I understood correctly, the dataset doesn't describe the cost of buildings, it only describes their area.

**Comment by matamadio** [comment]
>  1. What is the reason for listing the Thailand data a dataset, rather than just listing the whole [GHS-BUILT-S R2023A - GHS built-up surface grid, derived from Sentinel2 composite and Landsat, multitemporal (1975-2030) dataset](https://data.jrc.ec.europa.eu/dataset/9f06f36f-4b11-47ec-abb0-4f8b7b1d72ea) in line with the listing in the EU Joint Research Centre Data Catalogue?

The reason is that the global dataset is made of tiles, here those relative to the country were downloaded and merged together. In other cases there could be more processing compared to the source (e.g. change of resolution, value classification, clipping, others). Thus the download will point to the derived dataset, and not the original source.

>  2. Why is the [`exposure_cost` sheet](https://docs.google.com/spreadsheets/d/1SY0RFWhsIcpr_WSy1aRGhGBKoQkwSCFf/edit#gid=1909140703) populated? If I understood correctly, the dataset doesn't describe the cost of buildings, it only describes their area.

At the moment, the "cost" of exposure is limited to monetary currencies.
But the value represented by an exposure dataset might be intangible, or just a proxy to later calculate the economic value; in my experience it is actually pretty uncommon to use an exposure dataset that already comes into economic terms.
In this specific case it is a value of built-up area over total pixel area. In other cases, the value could be building height, or volume, population density or others. A range of different metrics could be represented by exposure, in order to measure the cost.

I see two options:

1. Put `cost` field as optional, use it only if actually a currency value. Don't specify exposure metric.
2. Add exposure `metric` field as open codelist

**Comment by duncandewhurst** [comment]
> > 1. What is the reason for listing the Thailand data a dataset, rather than just listing the whole [GHS-BUILT-S R2023A - GHS built-up surface grid, derived from Sentinel2 composite and Landsat, multitemporal (1975-2030) dataset](https://data.jrc.ec.europa.eu/dataset/9f06f36f-4b11-47ec-abb0-4f8b7b1d72ea) in line with the listing in the EU Joint Research Centre Data Catalogue?
> 
> The reason is that the global dataset is made of a large number of tiles; here, those relative to the country were downloaded and merged together. In other cases there could be more processing compared to the source (e.g. change of resolution, value classification, clipping, others). Thus the download will point to the derived dataset, and not the original source.

Ah, I see. So the actual processed/merged dataset is not linked in the example? If so, the value of `resources/0/url` should be left blank. Currently, it links to https://ghsl.jrc.ec.europa.eu/download.php?ds=bu, which is the download page for the whole dataset rather than the Thailand subset. The global dataset should be linked in `sources`.

> > 2. Why is the [`exposure_cost` sheet](https://docs.google.com/spreadsheets/d/1SY0RFWhsIcpr_WSy1aRGhGBKoQkwSCFf/edit#gid=1909140703) populated? If I understood correctly, the dataset doesn't describe the cost of buildings, it only describes their area.
> 
> At the moment, the "cost" of exposure is limited to monetary currencies. But the value represented by an exposure dataset might be intangible, or just a proxy to later calculate the economic value; in my experience it is actually pretty uncommon to use an exposure dataset that already comes into economic terms. In this specific case it is a value of built-up area over total pixel area. In other cases, the value could be building height, or volume, population density or others. A range of different metrics could be represented by exposure, in order to measure the cost.
> 
> I see two options:
> 
>     1. Put `cost` field as optional, use it only if actually a currency value. Don't specify exposure metric.
> 
>     2. Add exposure `metric` field as open codelist

I've created an issue on the standard repo, let's follow up there: https://github.com/GFDRR/rdl-standard/issues/194

**Comment by odscjen** [comment]
>If so, the value of resources/0/url should be left blank.

Unfortunately leaving this blank will cause the data to be reported as invalid, `resource.url` is a required field. We don't want to provide invalid examples, but equally we don't want to be providing semantically incorrect examples either. I see that we have a couple of options:

1. we create dummy url's that don't point to anywhere, E.g. http://example.com/GHS_THA. This option may require some additional explanation in the documentation as to what exactly `resource.url` should be pointing to.
2. we only create example's where there is already existing data with a url for the exact resource being described.

**Comment by odscjen** [comment]
@duncandewhurst the autopopulation of the links sheet might not be right, when I converted [FTH-snip example](https://docs.google.com/spreadsheets/d/1MDZq0VxhiRyzc7zpO0XcJYE8eGOdfcRo/edit#gid=965373431) it gave

```json
"links": [
    {
      "href": "https://raw.githubusercontent.com/GFDRR/rdl-standard/0__2__0/schema/rdls_schema.json",
      "rel": "describedby"
    }
  ]
```

but `describedby` should be `describedBy`

**Comment by matamadio** [comment]
> Unfortunately leaving this blank will cause the data to be reported as invalid, `resource.url` is a required field. We don't want to provide invalid examples, but equally we don't want to be providing semantically incorrect examples either. I see that we have a couple of options:
> 
>     1. we create dummy url's that don't point to anywhere, E.g. http://example.com/GHS_THA. This option may require some additional explanation in the documentation as to what exactly `resource.url` should be pointing to.
> 
>     2. we only create example's where there is already existing data with a url for the exact resource being described.

I had the exposure example file uploaded on sharepoint, though the link is accessible only for WB at the moment.

[THA_GHS-BU2020](https://worldbankgroup.sharepoint.com/:u:/s/ddh2/ESxHZg8fNLdOoB02IAj55cABdp3MWVONfaK8p-i8gmG3sA?e=Yv01iE)

**Comment by odscjen** [comment]
> I had the exposure example file uploaded on sharepoint, though the link is accessible only for WB at the moment.

Ah, ok. That will be fine for the actual data being uploaded to the data catalogue, but I think that for the case of examples it'd be best not to use non-open data. As in this case it's obviously useful to create the RDLS record for this data as it will exist, I'd recommend using a dummy url for the example. That way when you do upload it to the data catalogue you've already got the RDLS file and you'll just need to update the url to the real Sharepoint url

**Comment by odscjen** [comment]
@matamadio regarding the [rdls_hzd-FTH-snip example](https://docs.google.com/spreadsheets/d/1MDZq0VxhiRyzc7zpO0XcJYE8eGOdfcRo/edit#gid=965373431). Converting this to JSON and validating against the schema returns one major error:

* There are no `resources` provided which means the example is invalid as `resources` is a required object. Subsequently here is no link to the actual datasets as this would go into `resources`. 

The way that `resource` has been written it defines a _single_ resource, i.e. "An individual file or other form of data." But in this case you are describing a larger product which contains multiple resources that you cannot link to as they are behind a paywall so it's not a dataset that you're going to be able to publish. For this reason I don't think this is an appropriate example. 

(I'll create an additional comment in one of the documentation issues around how much detail we may want to include based on how the dataset being described will be available, e.g. in an open catalogue or behind some sort of access restriction.)

The appropriate example to use if you want to include the FATHOM global flood map is the one you have in [rdls_hzd-FTH-THA](https://docs.google.com/spreadsheets/d/1syZWJoooZ0oldD1dscNhuEsEr1VWHo_q/edit#gid=1748043487) where it has been used to create this specific datasource. 

The [rdls_hzd-FTH-THA](https://docs.google.com/spreadsheets/d/1syZWJoooZ0oldD1dscNhuEsEr1VWHo_q/edit#gid=1748043487) however suffers from the same issues as @duncandewhurst describes for the [Global Human Settlement layer (Thailand) example](https://docs.google.com/spreadsheets/d/1SY0RFWhsIcpr_WSy1aRGhGBKoQkwSCFf/edit#gid=633469357), namely that the `dataset` fields appear to be describing the source dataset rather than the dataset that the `resources` cover. The FATHOM map in this case should be in `sources` and the fields in the `dataset` sheet should be describing this Thailand specific version that has been created out of the FATHOM map rather than the FATHOM map in general.

Some additional errors in [rdls_hzd-FTH-THA](https://docs.google.com/spreadsheets/d/1syZWJoooZ0oldD1dscNhuEsEr1VWHo_q/edit#gid=1748043487):
* the values in `bbox` are separated by commas not semi-colons (I've corrected this one in the spreadsheet)
* no `resource.url`'s
* no `event.hazard`'s (but this is already being discussed in [#188](https://github.com/GFDRR/rdl-standard/issues/188) and [#192](https://github.com/GFDRR/rdl-standard/pull/192)

**Comment by matamadio** [comment]
> Ah, ok. That will be fine for the actual data being uploaded to the data catalogue, but I think that for the case of examples it'd be best not to use non-open data. As in this case it's obviously useful to create the RDLS record for this data as it will exist, I'd recommend using a dummy url for the example. That way when you do upload it to the data catalogue you've already got the RDLS file and you'll just need to update the url to the real Sharepoint url
> 
> EDIT: I've just seen you've created [GFDRR/rdl-standard#195](https://github.com/GFDRR/rdl-standard/issues/195) so we can wait for the resolution of this and hopefully there will be real url's to use soon :)

Could we host the demo data here on the GH?

**Comment by matamadio** [comment]
The idea for the "snippet" file was to provide a short json section of just key metadata in reference to the example figure, without actual data download. For schema reference / Example tabs only, replacing the current ones.

> The [rdls_hzd-FTH-THA](https://docs.google.com/spreadsheets/d/1syZWJoooZ0oldD1dscNhuEsEr1VWHo_q/edit#gid=1748043487) however suffers from the same issues as @duncandewhurst describes for the [Global Human Settlement layer (Thailand) example](https://docs.google.com/spreadsheets/d/1SY0RFWhsIcpr_WSy1aRGhGBKoQkwSCFf/edit#gid=633469357), namely that the dataset fields appear to be describing the source dataset rather than the dataset that the resources cover. The FATHOM map in this case should be in sources and the fields in the dataset sheet should be describing this Thailand specific version that has been created out of the FATHOM map rather than the FATHOM map in general.

I thought The only difference in metadata would be the subset coverage: Thailand instead of global. And yes, the resource should point to the download in our folder instead of source, but this is WIP.
In the case of Fathom data, there is no change or transformation either from source; it already comes as country datasets.

**Comment by odscjen** [comment]
> I thought the only difference in metadata would be the subset coverage: Thailand instead of global. 

Yes, in general this would be true and given you're other clarification about there being no change from the source I think actually the only field that doesn't quite make sense is `details`: you've put "The FATHOM flood-hazard model (previously known as SSBN), is a global gridded dataset of flood hazard produced at the global scale." but not mentioned in this field that the actual resource isn't global, i.e. you've described the FATHOM flood-hazard model rather than this specific subset of it. The fix is as simple as rewording this slightly to add a bit at the beginning:

"The Thailand country level dataset taken from the FATHOM flood-hazard model (previously known as SSBN). The FATHOM flood-hazard model is a global gridded dataset of flood hazard produced at the global scale. ..."

This just makes it a bit clearer that this isn't the entire FATHOM map.

> In the case of Fathom data, there is no change or transformation either from source; it already comes as country datasets.

Ah, okay so in that case you're right to put it in as the dataset fields rather than the source, but is this a dataset that can actually be made available? It looks like FATHOM is only available for a fee?

**Comment by odscjen** [comment]
> The idea for the "snippet" file was to provide a quick json example of just key metadata in reference to the example figure, without actual data download. 

I can see the logic in this but my worry is that it makes it seem as though you can use RDLS without providing the data, which is not something you'd want to imply.

**Comment by matamadio** [comment]
Agree on the need to specify a subset in the details.

> Ah, okay so in that case you're right to put it in as the dataset fields rather than the source, but is this a dataset that can actually be made available? It looks like FATHOM is only available for a fee?

Yes it is a commercial product, I chose it because it is the most frequently used for flood analysis across the bank, so it's relevant to show.
But yes, I can build a similar example with a similar open layer.

> I can see the logic in this but my worry is that it makes it seem as though you can use RDLS without providing the data, which is not something you'd want to imply.

Does it mean that [examples](https://github.com/GFDRR/rdl-standard/issues/135) will also need to have the actual resource download? Could it be just a dummy (empty resource links)?

**Comment by odscjen** [comment]
> Does it mean that https://github.com/GFDRR/rdl-standard/issues/135 will also need to have the actual resource download? Could it be just a dummy (empty resource links)?

A dummy link would be fine but I'd recommend making sure it looks like a dummy link, e.g. use http://example.com/YOUR_EXAMPLE

**Comment by matamadio** [comment]
The readme is ok, but should give reference to RDL at the beginning with links:

> A template for entering RDLS metadata in spreadsheet format. More information on the Risk Data Library Schema: https://riskdatalibrary.org/

**Comment by duncandewhurst** [comment]
> I've asked the devs what the correct syntax is in [OpenDataServices/flatten-tool#427](https://github.com/OpenDataServices/flatten-tool/issues/427). If it isn't possible to include commas or semi-colons within the values, we can update the input guidance for array fields and add a data validation warning if the cell's value includes commas or semi-colons.

It isn't possible to include commas or semicolons within array values so I've updated the input guidance for array fields.

**Comment by duncandewhurst** [comment]
> The readme is ok, we don't want to replicate the information found on docs; but it should give reference to RDL project at the beginning with links:
> 
> > A template for entering RDLS metadata in spreadsheet format.
> > More information on the Risk Data Library Schema: https://riskdatalibrary.org/
> > Guidelines for filling this metadata spreadhist and using the conversion tool: https://rdl-standard.readthedocs.io/
> 
> Please have fields description in multiple rows instead of one cell for easier reading, like in [rdls_hzd_AQD_docsample](https://docs.google.com/spreadsheets/d/1tXVnxte4pY6mwQIeEi0T2_ZRx4QWe4cA/edit?usp=sharing&ouid=104127175378111601700&rtpof=true&sd=true).

I've made those updates. At the same time, I've moved the readme content from the spreadsheet template to the README.md file in this repository and linked to it from the readme sheet in the template. I did that for three reasons:

- There are many limitations on formatting when creating the readme sheet programmatically, not least that it is only possible to have whole-cell hyperlinks.
- It is very time-consuming to maintain and update the code for creating the readme sheet programmatically, so it's better to have it in a Markdown file which anyone can easily edit.
- When users follow the readme link, they will always get the latest version.

**Comment by duncandewhurst** [comment]
@odscjen @matamadio I'm going to close this issue as I think that everything related to the template in this issue is now done. If there is anything outstanding relating to the example data or schema, please open an issue on the main rdl-standard repo. If there is anything outstanding relating to the spreadsheet template, please feel free to reopen this issue :-)
